name: esc_pos_utils_plus
description: Basic Flutter/Dart classes for ESC/POS printing. Ticket class generates ESC/POS commands that can be sent to a thermal printer.
version: 2.0.3
homepage: https://github.com/kechankrisna/esc_pos_utils_plus

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.17
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/esc_pos_utils_plus/resources/capabilities.json
